version: '3.8'

services:
  web:
    image: craftcms/nginx:8.0-dev
    container_name: blog_craft
    ports:
      - 8080:8080
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: blog_db
    env_file: .env
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=${CRAFT_DB_USER}
      - MYSQL_PASSWORD=${CRAFT_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${CRAFT_DB_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306" # Add this line to expose port 3306 for MySQL connections

