fieldLayouts:
  04ee00b8-5a86-4901-9f6e-b7f5ccd9024b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 633744b5-c386-40f7-871b-8ce89bb0b961
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2bc3319-c40e-4f85-8b66-e1e5ea75b7a6 # Text Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9050d783-56a9-42cc-9bc7-9c95de81f4d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a4d98ec-b2aa-4f11-959a-a2455b93e128
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a1ebdd44-f323-4c2e-8199-afe68c836ad3 # Articles
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
