fieldLayouts:
  535cf63d-b3fe-49da-b273-95c936aff72a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9231fe68-72b4-428d-b653-9349d4660f9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 12a53e9f-10e5-4c4d-9dba-57eaab3ef4c1
        userCondition: null
fs: files
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
