defaultPlacement: end
enableVersioning: true
handle: authors
name: Authors
propagationMethod: all
siteSettings:
  29f2de60-ede3-40d8-b625-a2d992c8f009: # blog
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
